name: Drand

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust: [stable, beta, nightly]
    
        steps:
          - uses: actions/checkout@v2
          - name: Install protobuf-compiler
            run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
          - run: rustup toolchain install ${{ matrix.rust }} && rustup default ${{ matrix.rust }} && rustup update ${{ matrix.rust }}
          - name: Build
            run: cargo build --release --verbose --features arkworks
          - name: Test
            run: cargo test --release --verbose --features arkworks
          - name: Lint
            run: cargo clippy -- -D warnings
          - name: Format
            run: cargo fmt -- --check

        
